const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('pob', {
  status: () => ipcRenderer.invoke('bridge-status'),
  selectBuild: () => ipcRenderer.invoke('select-build'),
  loadClipboardBuild: () => ipcRenderer.invoke('load-clipboard-build'),
  compareClipboardItem: () => ipcRenderer.invoke('compare-clipboard-item'),
  calculate: () => ipcRenderer.invoke('calculate'),
  hideOverlay: () => ipcRenderer.invoke('hide-overlay'),
  setIgnoreMouseEvents: (ignore) => ipcRenderer.invoke('set-ignore-mouse-events', ignore),
  poeStatus: () => ipcRenderer.invoke('poe-status'),
  poeConnect: () => ipcRenderer.invoke('poe-connect'),
  poeListCharacters: () => ipcRenderer.invoke('poe-list-characters'),
  poeSelectCharacter: (character) => ipcRenderer.invoke('poe-select-character', character),
  poeSync: () => ipcRenderer.invoke('poe-sync'),
  poeDisconnect: () => ipcRenderer.invoke('poe-disconnect'),
  onBridgeStatus: (callback) => ipcRenderer.on('bridge-status', (_event, value) => callback(value)),
  onItemComparisonStart: (callback) => ipcRenderer.on('item-comparison-start', () => callback()),
  onItemComparison: (callback) => ipcRenderer.on('item-comparison', (_event, value) => callback(value)),
  onItemComparisonError: (callback) => ipcRenderer.on('item-comparison-error', (_event, value) => callback(value)),
  onOverlayOpened: (callback) => ipcRenderer.on('overlay-opened', () => callback()),
  onOverlayClosed: (callback) => ipcRenderer.on('overlay-closed', () => callback()),
  onPoeStatus: (callback) => ipcRenderer.on('poe-status', (_event, value) => callback(value)),
  onPoeSyncStatus: (callback) => ipcRenderer.on('poe-sync-status', (_event, value) => callback(value)),
  onPoeCharacter: (callback) => ipcRenderer.on('poe-character', (_event, value) => callback(value)),
});
